server:
  port: 8082
  servlet:
    context-path: /payment-service
spring:
  jackson:
    time-zone: Asia/Shanghai
  application:
    name: payment-service
  data:
    redis:
      cluster:
        nodes:
          - 127.0.0.1:7001
          - 127.0.0.1:7002
          - 127.0.0.1:7003
          - 127.0.0.1:7004
          - 127.0.0.1:7005
          - 127.0.0.1:7006
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 64
          max-idle: 32
          min-idle: 16

  kafka:
    bootstrap-servers: localhost:9092,localhost:9094,localhost:9096
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      properties:
        enable.idempotence: true
    consumer:
      enable-auto-commit: false
      auto-offset-reset: earliest
      max-poll-records: 50
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.z.shop_common.order

  datasource:
    url: jdbc:mysql://localhost:3306/shop?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
    password: z7763882336
    driver-class-name: com.mysql.cj.jdbc.Driver

  hikari:
    maximum-pool-size: 20
    minimum-idle: 5
    idle-timeout: 600000
    connection-timeout: 30000

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.z.payment_service.domain
  configuration:
    map-underscore-to-camel-case: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/